### PR TITLE
Add roadmap

### PR DESCRIPTION
**Pull request by dwhswenson**
@diegoonolasco sent me the roadmap image this morning; this adds it to the website.

A few thoughts for possible future improvements:

* At some point it would be nice to generate this as an SVG. That would give us both better resolution and (I think?) might make it so that the text gets indexed by search engines.
* We might reframe the content for this context. Here we're trying to advertise to potential sponsors, so some things that are more about justifying time previously spent (like team building) are less relevant, whereas the things we've actually delivered are very relevant.
* Currently, these follow @richardjgowers's convention of setting the label according to the month that it is delivered in (at the beginning of the month). I think the visualization would imply to people that we spent the given month accomplishing that task. OTOH, that makes us look like we're a month ahead of schedule, so that's not so bad! 😂

### CODE REVIEW

**Review by richardjgowers — CHANGES_REQUESTED** [review]
Can we redo the colours to the website palette?

**Comment by diegoonolasco** [comment]
I just made a new version. Please, take a look and let me know if it's enough.
https://docs.google.com/presentation/d/1f70nXKq4V9E4ywNIFLO_uN44dNakOhLqLdItcpk8ZKI/edit?usp=sharing

**Review by richardjgowers — APPROVED** [review]
awesome thanks!

**Review by IAlibay — APPROVED** [review]
SVG 💖

**Comment by dwhswenson** [comment]
Two approvals is enough (actually, 1 probably was). Merging this.

**Comment by diegoonolasco** [comment]
Thanks a lot @dwhswenson!

**Pull request merged**
