### PR TITLE
Remove DN from team page

### PR DESCRIPTION
**Pull request by dwhswenson**
I guess it is time.

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]

**Comment by IAlibay** [comment]
Is it worth considering having an emerti section? Would be good to have a record of all the folks that were involved with the project at some point or another.

**Review by mikemhenry — APPROVED** [review]
:broken_heart:

**Comment by IAlibay** [comment]
> Is it worth considering having an emerti section? Would be good to have a record of all the folks that were involved with the project at some point or another.

Although we merged - thoughts on this, it would be good for us not to forget about it if it's something we want to do.

**Comment by RiesBen** [comment]
I really like the emeriti section :) and would like to second this. Do you think on the team page just below? We should also ask people, if they want to be listed there.

**Comment by RiesBen** [comment]
@IAlibay  see here #51

**Pull request merged**
