### PR TITLE
Revert "benOnBoard"

### PR DESCRIPTION
**Pull request by RiesBen**
Reverts OpenFreeEnergy/openfreeenergy.github.io#31 
need to add changes !

### CODE REVIEW

**Comment by dwhswenson** [comment]
Revert is needed unless changes are made quickly -- the page is broken.

Changes needed are just to add a couple spaces before each line in @RiesBen's blurb so that the YAML parses correctly.

**Comment by RiesBen** [comment]
hihi you guys are too fast! I was changing stuff on the branch :)

**Comment by RiesBen** [comment]
> Changes needed are just to add a couple spaces before each line in @RiesBen's blurb so that the YAML parses correctly.

Sorry saw your suggestion and thought it was already in the code... currently working on it. should be fixed in 2min ;)

**Comment by dwhswenson** [comment]
No worries... I don't think we're getting THAT many visitors per hour to the site! 🤣  Besides, while broken, it doesn't break it in too terrible of a way.

**Comment by RiesBen** [comment]
=) fixed ! only thee picture looks super stupid ^^

**Comment by dwhswenson** [comment]
No worse than the rest of us. Are we making a rule now that the bottom row must have beards in their pictures, and top row may not?

**Pull request closed without merging**
